### ISSUE TITLE
 Controller operation failed: 502 Error CF-ServiceBrokerRequestRejected(10001)

### ISSUE THREAD

**Issue by dileepsaccount** [SAP-samples/btp-cap-genai-rag#20]
While deploying the app, getting Error determining actions to execute on service "ai-try-out-space-aisaas-com-hdi-container": Controller operation failed: 502 Error determining actions to execute on service "ai-try-out-space-aisaas-com-hdi-container": CF-ServiceBrokerRequestRejected(10001): Service broker error: Service broker hana-broker failed with: {}

Full log attached
[OPERATION.log](https://github.com/SAP-samples/btp-cap-genai-rag/files/15230797/OPERATION.log)

**Comment by kay-schmitteckert** [comment]
Hi @dileepsaccount,

since there is no reason for the error, I would assume either some temporary issue or wrong configuration. Could you double check?

Best
Kay

**Comment by dileepsaccount** [comment]
Hi @kay-schmitteckert , I have double checked everything from my end and everything looks good as per the documentation. I can provide you the sub account access, do you like to look at it once?

**Comment by kay-schmitteckert** [comment]
@dileepsaccount, we did some updates on the code base. At least with this version, we dont see any issues.
Hope it helps
Kay
