### ISSUE TITLE
Not able to push sample mails

### ISSUE THREAD

**Issue by shumagundam** [SAP-samples/btp-cap-genai-rag#23]
I was able to execute the **GET XSUAA TOKEN** request using requests-btp-private.htpp file and successfully retrieved the xsuaa token. But when I tried to execute **ADD MAILS** request, I received "Internal Server Error 500".
Further checking the logs on "ai-srv-dev", it appears the error is related to undefined property on mail-insights-service.js line 190
![Screenshot 2024-06-10 at 10 28 41 AM](https://github.com/SAP-samples/btp-cap-genai-rag/assets/13772323/846b7d52-6f49-4492-ae3a-c89a12813d43)

**Comment by kay-schmitteckert** [comment]
Hi @shumagundam, looking at your other logs, I see a lot of 403. It seems that any part of the flow is not configured properly and my assumption would be the connection from CAP to SAP AI Core and the LLMs. Can you check with SAP AI Launchpad (or with the API of SAP AI Core) if the resource group and model deployments are available? If so, can you double check your destination pointing to the SAP AI Core instance?

Best
Kay
