### ISSUE TITLE
Generative AI Hub Setup not working

### ISSUE THREAD

**Issue by rrforever88** [SAP-samples/btp-cap-genai-rag#29]
Hello,

I'm trying to follow along and when I get to the generativeAIhub section, I receive and error. 

https://github.com/SAP-samples/btp-cap-genai-rag/blob/main/docs/tutorial/2-setup/4-generativeAIhub.md

Thanks,
Chris

**Comment by jmsrpp** [comment]
The repo has been refactored so the AI core plan gets created automatically with deployment of the MTA and binding to the app.

**Comment by jmsrpp** [comment]
Hi Chris,Can you post the details about the error you’re receiving?Thanks,Jim ***@***.*** Nov 14, 2024, at 5:30 PM, Chris Nelson ***@***.***> wrote:﻿
Hello,
I'm trying to follow along and when I get to the generativeAIhub section, I receive and error.
https://github.com/SAP-samples/btp-cap-genai-rag/blob/main/docs/tutorial/2-setup/4-generativeAIhub.md
Thanks,
Chris
