### ISSUE TITLE
npm run watch in Hybrid mode not working 

### ISSUE THREAD

**Issue by gekko68** [SAP-samples/btp-cap-genai-rag#36]
Following the documentation 2-HybridDev.md :

```# Run in ./single-tenant/code #

npm run watch
```

causes :

<img width="684" alt="image" src="https://github.com/user-attachments/assets/7db0fd93-4db3-451b-b53a-bf2f9a4bfc73">

**Comment by kay-schmitteckert** [comment]
Hi @gekko68,

Please have a look at this docu: https://cap.cloud.sap/docs/node.js/typescript#cds-tsx

Best
